### ISSUE TITLE
Glyphicons not working

### ISSUE THREAD

**Issue by yoshkosh** [iguchi1124/honoka-rails#1]
Glyphicons are not working on my development env.
- ruby 2.2.4
- rails 4.2.4
- honoka-rails 3.3.6.1
- sprockets-rails 3.0.0

Screenshot:
![capture](https://cloud.githubusercontent.com/assets/16587544/12468443/1dec23b8-c027-11e5-88e6-d6878758e6ea.png)

A quick fix to $icon-font-path seems to be working.

```
// assets/stylesheets/application.scss

$icon-font-path: "bootstrap/";

@import "bootstrap-sprockets";
@import "honoka";
```

**Comment by iguchi1124** [comment]
@walakka-jp Thanks to your bug reports! :smile:
