### ISSUE TITLE
MIT License?

### ISSUE THREAD

**Issue by windyakin** [iguchi1124/honoka-rails#2]
MIT License is ...

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

So, this gem is necessary to write the original banner of Honoka and Bootstrap at the top of the file.

Example) Honoka Banner

``` css
/*!
 * Honoka v3.3.6-a
 * Website http://honokak.osaka/
 * Copyright 2015 windyakin
 * The MIT License
 */
/*!
 * Bootstrap v3.3.6 (http://getbootstrap.com)
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under the MIT license
 */
```

**Comment by iguchi1124** [comment]
@windyakin 

Thanks!

I added original license comment.

Rails is always compressing css. But license comments will be remained in the production code.

Please check if it is good.

**Comment by iguchi1124** [comment]
close this issue if PR #3 was merged into master.

**Comment by windyakin** [comment]
[![LGTM](http://lgtm.in/p/u3kOtoUpq)](http://lgtm.in/i/u3kOtoUpq)
